spring:
  profiles: dev1
  application:
    name: service-eureka
server:
  port: 9001
  tomcat:
    max-threads: 512
eureka:
  instance:
    hostname: eureka-01.mufan.com
  client:
#    registerWithEureka: true
#    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-02.mufan.com:9002/eureka/,http://eureka-03.mufan.com:9003/eureka/

---

spring:
  profiles: dev2
  application:
    name: service-eureka
server:
  port: 9002
  tomcat:
    max-threads: 512
eureka:
  instance:
    hostname: eureka-02.mufan.com
  client:
    serviceUrl:
      defaultZone: http://eureka-01.mufan.com:9001/eureka/,http://eureka-03.mufan.com:9003/eureka/


---


spring:
  profiles: dev3
  application:
    name: service-eureka
server:
  port: 9003
  tomcat:
    max-threads: 512
eureka:
  instance:
    hostname: eureka-03.mufan.com
  client:
    serviceUrl:
      defaultZone: http://eureka-01.mufan.com:9001/eureka/,http://eureka-02.mufan.com:9002/eureka/
